// src/components/formal/project/ProjectStatus.vue
<template>
    <div>
      <font-awesome-icon :class="(done ? 'done': 'in-dev')" :icon="(done ? 'check': 'code')"/>
      {{ done ? doneText[lang] : inDevText[lang] }}
    </div>
</template>

<script>
import {FontAwesomeIcon} from "@fortawesome/vue-fontawesome";

export default {
  name: "ProjectStatus",
  components: {FontAwesomeIcon},
  props: {
    done: Boolean,
    lang: String
  },
  data() {
    return {
      doneText: {
        en: 'Done',
        fr: 'Fini'
      },
      inDevText: {
        en: 'In development',
        fr: 'En développement'
      }
    }
  }
}
</script>

<style scoped>
.pastille {
  height: 10px;
  width: 10px;
  border-radius: 4px;
}
.in-dev {
  color: orange;
}

.done {
  color: lime;
}

div {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 4px;
  background: #3f4148;
  border-radius: 4px;
  width: fit-content;

}
</style>

// src/views/FormalView/components/ProjectStatus.svelte
<script lang="ts">
    import Fa from "svelte-fa";
    import {faCheck, faCode} from "@fortawesome/free-solid-svg-icons";
    import {Lang} from "@stores";

    // const statusText = {
    //     done: {
    //         fr: "Fini",
    //         en: "Done"
    //     },
    //     inDev: {
    //         fr: "En développement",
    //         en: "In development"
    //     }
    // }

    export let status: Formal.Project["status"];
</script>

<div>
<!--    <Fa icon={done ? faCheck : faCode} class={done ? "done" : "in-dev"}/>-->
<!--    <span>{done ? statusText.done[$Lang] : statusText.inDev[$Lang]}</span>-->
<div>
    {status}
</div>
</div>


<style>
    div {
        padding: 4px 6px;
        background: #3a3a3a;
        width: fit-content;
        border-radius: 6px;
    }
</style>
