// src/views/CLIView.vue
<template>
  <div id="terminal">
    <CLIWelcome v-if="!cleared"/>
    <p>
      <template v-for="command in history" :key="command">
        <template v-if="command.path">
          <CLIPromptText :path="command.path"/>{{ command.path ? command.input : null }}
          <br v-if="command.result"/>
        </template>
        <template v-for="part in command.result" v-bind:key="part">
          <CLIResultParser v-if="part" :result="part"/>
        </template>
        <br v-if="!command.result"/>
      </template>
    </p>
    <div class="prompt-wrapper" v-if="!loading" @click="$refs.prompt.focus()">
      <p>
        <CLIPromptText :path="path"/>
        <span
            @keydown.enter.prevent="runCommand(false)"
            @keydown.up.down.prevent="inputArrowHooker"
            @keydown.tab.prevent
            @paste="pasteHooker"
            contenteditable="true"
            spellcheck="false"
            ref="prompt"
            class="prompt"
        >
      </span>
      </p>
    </div>
    <CLILoadingIndicator v-else/>
  </div>

</template>

<script>
import runCommand from "@/utils/cli/runCommand";
import CLIWelcome from "@/components/cli/CLIWelcome.vue";
import CLIPromptText from "@/components/cli/CLIPromptText.vue";
import CLIResultParser from "@/components/cli/CLIResultParser.vue";
import CLILoadingIndicator from "@/components/cli/CLILoadingIndicator.vue";
import cls from "@/utils/cli/commands/cls";

export default {
  name: "CLIView",
  components: {
    CLILoadingIndicator,
    CLIResultParser,
    CLIPromptText,
    CLIWelcome
  },
  data()
  {
    return {
      loading: true,
      input: '',
      stackState: -1,
      isShiftDown: false,
      isControlDown: false
    };
  },
  computed: {
    path()
    {
      return this.$store.state.path;
    },
    history()
    {
      return this.$store.state.history;
    },
    previousCmdStack()
    {
      return this.$store.state.previousCmdStack;
    },
    cleared()
    {
      return this.$store.state.cleared;
    },
  },
  methods: {
    async runCommand(auto)
    {
      if (auto === false)
        this.input = this.$refs.prompt.innerText;

      this.loading = true;
      await runCommand(this.input);
      this.input = '';
      this.stackState = -1;
      this.loading = false;
    },
    inputArrowHooker(e)
    {
      if (e.key === 'ArrowUp') {
        if (this.stackState + 1 < this.previousCmdStack.length) {
          this.stackState++;
          this.$refs.prompt.innerText = this.previousCmdStack[this.stackState];
          this.promptFocusCaretEnd();
        }
      }
      else if (e.key === 'ArrowDown') {
        if (this.stackState > 0) {
          this.stackState--;
          this.$refs.prompt.innerText = this.previousCmdStack[this.stackState];
          this.promptFocusCaretEnd();
        }
        else if (this.stackState === 0) {
          this.stackState--;
          this.$refs.prompt.innerText = '';
        }
      }
    },
    onKeyDown(e)
    {
      if (e.key === 'l') {
        if (this.isControlDown && !this.isShiftDown) {
          e.preventDefault();
          cls();
        }
      }

      if (e.key === 'Control') { // Need to modify that for macOS support
        this.isControlDown = true;
        return;
      }

      window.scrollTo(0, document.body.scrollHeight);
      if (document.activeElement !== this.$refs.prompt) {
        if (e.key === 'Shift') {
          this.isShiftDown = true;
          return;
        }

        if (e.key.startsWith('Arrow'))
          if (this.isShiftDown)
            return;

        if (!this.loading && !(this.isControlDown && e.key === 'c')) {
          this.promptFocusCaretEnd();
          window.scrollTo(0, document.body.scrollHeight);
        }
      }
    },
    onKeyUp(e)
    {
      if (e.key === 'Shift')
        this.isShiftDown = false;

      if (e.key === 'Control')
        this.isControlDown = false;
    },
    // tabHooker(e) {
    //   console.log(e)
    // }
    async pasteHooker(e)
    {
      const data = e.clipboardData.getData('Text').replaceAll('\r', '');

      if (data.includes('\n')) {
        const inputs = data.split('\n');

        for (let i = 0; i < inputs.length - 1; i++) {
          this.input = inputs[i]
          await this.runCommand(true)
        }

        this.$refs.prompt.innerText = inputs[inputs.length - 1];
      }
      else {
        this.$refs.prompt.innerText += data;
      }

      e.preventDefault();
      this.promptFocusCaretEnd();
    },
    promptFocusCaretEnd() {
      const target = this.$refs.prompt;

      //https://stackoverflow.com/questions/1125292/how-to-move-cursor-to-end-of-contenteditable-entity
      const range = document.createRange();
      const sel = window.getSelection();
      range.selectNodeContents(target);
      range.collapse(false);
      sel.removeAllRanges();
      sel.addRange(range);
      target.focus();
      range.detach(); // optimization

      // set scroll to the end if multiline
      target.scrollTop = target.scrollHeight;
    }
  },
  mounted()
  {
    fetch('/fileTree.json')
        .then(response => response.json())
        .then(data => {
          this.$store.commit('setFileTree', {"~": { type: "folder", children: data }});
          this.loading = false;
        });

    document.querySelector('html').setAttribute("lang", 'en');
    document.title = "CLI - Aurélien DUMAY";

    document.addEventListener('keydown', this.onKeyDown)
    document.addEventListener('keyup', this.onKeyUp);
  },
  updated()
  {
    const prompt = this.$refs.prompt;

    if (prompt)
      prompt.focus();

    window.scrollTo(0, document.body.scrollHeight);
  },
  beforeUnmount()
  {
    document.removeEventListener('keydown', this.onKeyDown)
    document.removeEventListener('keyup', this.onKeyUp);
  }
};
</script>


<style scoped>
#terminal {
  font-family: monospace;
  color: white;
  padding: 20px 20px 0 20px;
  font-size: 20px;
  min-height: 100vh;
  box-sizing: border-box;
  display: flex;
  flex-direction: column;
}

.loader {
  color: gray;
}

p, a, span {
  word-break: break-all;
}

@media (max-width: 420px) {
  #terminal {
    font-size: 12px;
  }
}

.prompt {
  caret-color: lime;
}

.prompt-wrapper {
  flex: 1;
  padding-bottom: 20px;
}

[contenteditable] {
  outline: none;
}
</style>

// src/views/CLIView/CLIView.svelte
<script lang="ts">
    import {afterUpdate, onMount} from "svelte";

    import {Cleared, DeviceInfo, InputHistoryStack, ExecutionHistory, FileTree} from "@stores";
    import clear from "@cli/bin/clear";

    import WelcomeText from "./components/WelcomeText.svelte";
    import PromptText from "./components/PromptText.svelte";
    import OutputParser from "./components/OutputParser.svelte";
    import LoadingIndicator from "@core-components/LoadingIndicator.svelte";

    import run from "@cli/core/run";
    import {AURE_CLI_ASCII_ART} from "@utils/const";

    // A span element with contenteditable property set to true -> gets input
    let inputEl: HTMLSpanElement;

    // Disables the input when set to false
    let loading: boolean = true;

    // To navigate through the input history stack
    let currentHistoryStackIndex: number = -1;
    // The last saved value -> saved when incrementing currentHistoryStackIndex
    // and displayed when currentHistoryStackIndex is back to -1
    let inputSavedValue: string = "";

    /**
     * On key down anywhere on the page
     * @param e
     */
    async function handleKeyDown(e: Event): Promise<void>
    {
        const key = (e as KeyboardEvent).key;
        const isControlDown = (e as KeyboardEvent).ctrlKey;
        const isCommandDown = $DeviceInfo?.keyboard === "apple"
            ? (e as KeyboardEvent).metaKey
            : (e as KeyboardEvent).ctrlKey;
        const isShiftDown = (e as KeyboardEvent).shiftKey;

        // Whether the input is focused or not
        switch (key.toLowerCase()) {
            case "control":
            case "command":
            case "shift":
                return;
            // Prevents the tab key from updating the focus
            case "tab":
                e.preventDefault();
                return;
            // May clear the history when control is pressed
            case "l":
                if (isControlDown && !isShiftDown) {
                    e.preventDefault();
                    clear();
                }
                break;
            case "b":
            case "u":
            case "i":
                if (isCommandDown)
                    e.preventDefault();
                break;
        }
        // if the input is NOT focused
        if (document.activeElement !== inputEl) {

            const isCopyingText = isCommandDown && key.toLowerCase() === "c";
            const isSelectingText = isShiftDown && key.startsWith("Arrow");

            if (!loading && !isCopyingText && !isSelectingText) {
                focusInputAndMoveCaretAtTheEnd();
                window.scrollTo(0, document.body.scrollHeight);
            }
        }
        // if the input IS focused
        else {
            // Sets the currentHistoryStackIndex back to -1 on previous input edition
            if (currentHistoryStackIndex !== -1 && inputEl.innerText !== $InputHistoryStack[currentHistoryStackIndex])
                currentHistoryStackIndex = -1;

            if (key === "ArrowUp" || key === "ArrowDown") {
                e.preventDefault();
                navigateThroughHistoryStack(key);
            }

            // RUNS A COMMAND
            if (key === "Enter") {
                e.preventDefault();
                // isLoading animation + disables the input
                loading = true;
                // Runs the input (sends the current path)
                await run(inputEl.innerText);
                // So we need to reset the currentHistoryStackIndex
                currentHistoryStackIndex = -1;
                loading = false;
            }

        }
    }

    async function handlePaste(e: ClipboardEvent)
    {
        if (!e.clipboardData)
            return;

        const data = e.clipboardData?.getData('Text').replaceAll('\r', '');

        if (data.includes('\n')) {
            const inputs = data.split('\n');
            const inputLastIdx = inputs.length - 1;

            for (let i = 0; i < inputLastIdx; i++) {
                await run(inputs[i]);
            }

            inputEl.innerText = inputs[inputLastIdx];
            focusInputAndMoveCaretAtTheEnd();
        }
        else if (data) {
            inputEl.innerText = data;
            focusInputAndMoveCaretAtTheEnd();
        }

        e.preventDefault();
    }

    function navigateThroughHistoryStack(key: "ArrowUp" | "ArrowDown")
    {
        if (key === "ArrowUp") { // moves backward in the input history
            if (currentHistoryStackIndex + 1 < $InputHistoryStack.length) {
                if (currentHistoryStackIndex === -1)
                    inputSavedValue = inputEl.innerText;

                inputEl.innerText = $InputHistoryStack[++currentHistoryStackIndex];
            }
        }
        else { // ArrowDown - moves forward in the input history
            if (currentHistoryStackIndex > 0)
                inputEl.innerText = $InputHistoryStack[--currentHistoryStackIndex];

            else if (currentHistoryStackIndex === 0) {
                inputEl.innerText = inputSavedValue;
                currentHistoryStackIndex = -1;
            }
        }

        focusInputAndMoveCaretAtTheEnd();
    }


    function focusInputAndMoveCaretAtTheEnd()
    {
        //https://stackoverflow.com/questions/1125292/how-to-move-cursor-to-end-of-contenteditable-entity
        const range = document.createRange();
        const sel = window.getSelection();

        if (!sel)
            return;

        range.selectNodeContents(inputEl);
        range.collapse(false);
        sel.removeAllRanges();
        sel.addRange(range);
        inputEl.focus();
        range.detach(); // optimization

        // set scroll to the end if multiline
        inputEl.scrollTop = inputEl.scrollHeight;
    }

    onMount(async () => {
        console.info("%c" + AURE_CLI_ASCII_ART + import.meta.env.VITE_VERSION, 'color: cyan');

        try {
            const res = await fetch("/fileTree.json");
            $FileTree = await res.json() as CLI.FileTree;
            loading = false;
        }
        catch (e) {}
    })

    afterUpdate(() => {
        if (inputEl) {
            window.scrollTo(0, document.body.scrollHeight);
            inputEl.focus();
        }
    });
</script>

<svelte:window on:keydown={handleKeyDown}/>
<main id="cli">
    {#if !$Cleared}
        <WelcomeText/>
    {/if}
    {#each $ExecutionHistory as previousElement}
        <div>
            <PromptText path={previousElement.path}/><!--
            --><span class="previous-input">{previousElement.input}</span>
            {#if previousElement.output}
                {#each previousElement.output as output, index (index)}
                    <OutputParser {output}/>
                {/each}
            {/if}
        </div>
    {/each}
    {#if (loading)}
        <LoadingIndicator withMargin/>
    {:else}
        <!-- svelte-ignore a11y-no-static-element-interactions a11y-click-events-have-key-events -->
        <div class="prompt-wrapper" on:click={() => inputEl.focus()}>
            <!-- Workaround: Using HTML comments to prevent unwanted spaces -->
            <PromptText/><!--
            --><span
                on:paste={handlePaste}
                bind:this={inputEl}
                contenteditable="true"
                spellcheck="false"
                class="input"
            ></span>
        </div>
    {/if}
</main>

<style>
    main {
        padding: var(--medium-padding) var(--medium-padding) 0 var(--medium-padding);
        font-size: var(--text-font-size);
        display: flex;
        flex-direction: column;
        box-sizing: border-box;
        min-height: 100vh;
    }

    .input {
        caret-color: var(--cyan);
        outline: none;
        word-break: break-all;
        word-wrap: break-word;
        white-space: break-spaces;
    }

    .prompt-wrapper {
        flex: 1;
        padding-bottom: var(--medium-spacing);
    }

    .previous-input {
        white-space: break-spaces;
    }
</style>
